package common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUseronline<M extends BaseUseronline<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setChatroom(java.lang.String chatroom) {
		set("chatroom", chatroom);
		return (M)this;
	}
	
	public java.lang.String getChatroom() {
		return getStr("chatroom");
	}

	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M)this;
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}

	public M setLastchattime(java.util.Date lastchattime) {
		set("lastchattime", lastchattime);
		return (M)this;
	}
	
	public java.util.Date getLastchattime() {
		return get("lastchattime");
	}

	public M setDenyroom(java.lang.String denyroom) {
		set("denyroom", denyroom);
		return (M)this;
	}
	
	public java.lang.String getDenyroom() {
		return getStr("denyroom");
	}

	public M setDenytime(java.util.Date denytime) {
		set("denytime", denytime);
		return (M)this;
	}
	
	public java.util.Date getDenytime() {
		return get("denytime");
	}

}
