package common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setUserid(java.lang.Integer userid) {
		set("userid", userid);
		return (M)this;
	}
	
	public java.lang.Integer getUserid() {
		return getInt("userid");
	}

	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M)this;
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}

	public M setAge(java.lang.Integer age) {
		set("age", age);
		return (M)this;
	}
	
	public java.lang.Integer getAge() {
		return getInt("age");
	}

	public M setEMail(java.lang.String eMail) {
		set("e_mail", eMail);
		return (M)this;
	}
	
	public java.lang.String getEMail() {
		return getStr("e_mail");
	}

	public M setLoginname(java.lang.String loginname) {
		set("loginname", loginname);
		return (M)this;
	}
	
	public java.lang.String getLoginname() {
		return getStr("loginname");
	}

	public M setSchoolid(java.lang.Integer schoolid) {
		set("schoolid", schoolid);
		return (M)this;
	}
	
	public java.lang.Integer getSchoolid() {
		return getInt("schoolid");
	}

}
