package common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("msginfo", "id", Msginfo.class);
		arp.addMapping("user", "userid", User.class);
		arp.addMapping("userinfo", "id", Userinfo.class);
		arp.addMapping("useronline", "id", Useronline.class);
	}
}

