package common.model;

import common.model.base.BaseMsginfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Msginfo extends BaseMsginfo<Msginfo> {
	public static final Msginfo dao = new Msginfo().dao();
}
