package common.model;

import common.model.base.BaseUseronline;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Useronline extends BaseUseronline<Useronline> {
	public static final Useronline dao = new Useronline().dao();
}
